apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: epa
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001