apiVersion: apps/v1
kind: Deployment
metadata:
  name: epa
  labels:
    app: epa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: epa
  template:
    metadata:
      labels:
        app: epa
    spec:
      containers:
      - image: ./Dockerfile
        name: epa
        # imagePullPolicy: Never
        ports:
        - containerPort: 5000
      restartPolicy: Always
